import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import React, { useState } from 'react';
import { NGROK_URL } from '../constants';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [username, setUsername] = useState('');
  const [orgName, setOrgName] = useState('');
  const login = async (orgName: string) => {
    window.FB.login(async (res) => {
      console.log(res);
      if (res.status === 'connected') {
        const response = await fetch(`${NGROK_URL}/integration`, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            access_token: res.authResponse.accessToken,
            orgName,
          }),
        });
        console.log(await response.json());
      }
    }),
      {
        scope:
          'public_profile,pages_show_list,business_management,pages_messaging,instagram_basic,instagram_manage_comments,instagram_content_publish,instagram_manage_messages,pages_read_engagement,pages_manage_metadata',
      };
  };

  const logout = () => {
    window.FB.logout((res) => {
      console.log(res);
    });
  };

  const handleUsernameSubmit = async (orgName: string) => {
    const res = await fetch(`${NGROK_URL}/social/igUsername`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ username: username, orgName: orgName }),
    });
    console.log(await res.json());
    setUsername('');
  };

  const handleOrgNameSubmit = async () => {
    const res = await fetch(`${NGROK_URL}/organisation`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ orgName: orgName }),
    });
    console.log(await res.json());
    setOrgName('');
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <button onClick={() => login('org1')}>org1</button>
        <button onClick={() => login('org2')}>org2</button>
        <button onClick={() => logout()}>logout</button>
        <input
          value={orgName}
          onChange={(e) => setOrgName(e.target.value)}
        ></input>
        <button
          onClick={() => {
            handleOrgNameSubmit();
          }}
        >
          org name
        </button>
        <input
          value={username}
          onChange={(e) => setUsername(e.target.value)}
        ></input>
        <button
          onClick={() => {
            handleUsernameSubmit('org1');
          }}
        >
          username for org1
        </button>
        <button
          onClick={() => {
            handleUsernameSubmit('org2');
          }}
        >
          username for org2
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
