import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import React, { useEffect, useState } from 'react';
import { NGROK_URL } from '../constants';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  const [value, setValue] = useState('');
  let pageId: string;
  let accountId: string;
  const login = async () => {
    window.FB.login(async (res) => {
      console.log(res);
      if (res.status === 'connected') {
        // const pageIdRes = await fetch(
        //   `${NGROK_URL}/api/getPageId?token=${res.authResponse.accessToken}`
        // );
        // const pageIdObj = await pageIdRes.json();
        // pageId = pageIdObj.data[0].id;
        // const accountIdRes = await fetch(
        //   `${NGROK_URL}/api/getAccountId?pageId=${pageId}&token=${res.authResponse.accessToken}`
        // );
        // const accountIdObj = await accountIdRes.json();
        // accountId = accountIdObj.instagram_business_account.id;
        // console.log(pageIdObj, accountIdObj);
        // console.log(pageId, accountId);
      }
    }),
      {
        scope:
          'public_profile,pages_show_list,business_management,pages_messaging,instagram_basic,instagram_manage_comments,instagram_content_publish,instagram_manage_messages,pages_read_engagement,pages_manage_metadata',
      };
  };

  const handleOnSubmit = async () => {
    const res = await fetch(`${NGROK_URL}/social/igUsername`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({ username: value }),
    });
    console.log(await res.json());
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
        <button onClick={() => login()}>login</button>
        <input value={value} onChange={(e) => setValue(e.target.value)}></input>
        <button
          onClick={() => {
            handleOnSubmit();
          }}
        >
          submit
        </button>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
};

export default Home;
